seed: 42
do_train: True 
do_predict: True

# top-level config #
paradigm: seq2seq
task_name: EAE
dataset_name: RichERE
language: English
test_exists_labels: True

# file path #
output_dir: output/RichERE
type2id_path: ../../data/processed/RichERE/label2id.json
role2id_path: ../../data/processed/RichERE/role2id.json
train_file: ../../data/processed/RichERE/train.unified.jsonl
validation_file: ../../data/processed/RichERE/valid.unified.jsonl
test_file: ../../data/processed/RichERE/test.unified.jsonl
# event detection predictions
golden_trigger: True 
train_pred_file: output/RichERE/ED/token_classification/bert-base-uncased-marker/train_preds.json
validation_pred_file: output/RichERE/ED/token_classification/bert-base-uncased-marker/valid_preds.json
test_pred_file: output/RichERE/ED/token_classification/bert-base-uncased-marker/test_preds.json

# config for data processor # 
truncate_in_batch: True 
return_token_type_ids: False 
truncate_seq2seq_output: True

# model config #
model_type: t5
model_name_or_path: t5-base
backbone_checkpoint_path: t5-base
hidden_size: 768
aggregation: none

# training config #
num_train_epochs: 10
max_seq_length: 160
max_out_length: 128
dataloader_num_workers: 2
early_stopping_patience: 100

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True 
ignore_pad_token_for_loss: True 

per_device_train_batch_size: 8
per_device_eval_batch_size: 20
gradient_accumulation_steps: 2
# eval_accumulation_steps: 4
learning_rate: 1.0e-4
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1.0
optim: adamw_torch
# lr_scheduler_type: constant

load_best_model_at_end: True
metric_for_best_model: micro_f1 
greater_is_better: True 

logging_strategy: steps
logging_steps: 100
evaluation_strategy: epoch
eval_steps: 500
save_strategy: epoch
save_steps: 500

# split inference #
split_infer: False
split_infer_size: 5000

